apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ad
  description: Artist Lookup
  tags:
    - java
    - data
  links:
    - url: https://example.com/user
      title: Examples Users
      icon: user
annotations:
  backstage.io/kubernetes-label-selector: 'app=checkoutservice'
spec:
  type: service
  lifecycle: experimental
  owner: cy
  system: artist-engagement-portal
  dependsOn: ['component:podcast-api']
